class ReservationData{
  static String resprice;
  static String rescoin='Currency';
  static String pickuploc='Pick Up Location';
  static String pickupdate;
  static String returndate;
  static String returnlocation='Return Location';
  static String pickuptime;
  static String returntime;
  static int ReservationDaysCount;
  static int totaldaysfree;
  static  String passager;
  static String year;
  static String bag;
  static String coin;
  static String door;
  static String resstatus;
  static String cartype;
  static String transmission;
  static String  imagecar ;
  static String price;
  static bool updatepickuplocation;
  static String caryear='All';
  static String carcategory='All';
  static bool Airport=false;
  static List<String>Coins=[];
  static List<String>CarCategory=['All'];
  static List<String>CarYear=['All'];
  static bool colorred,colorblack,coloryellow,colorwhite,colorgrey,colorgreen,colorblue,colorsliver;
  static List<String>optionname=[];
  static List<String>optioncount=[];
  static List<String>optionprice=[];
  static List<String>inssuracelistname=[];
  static List<String>inssuranceprice=[];
  static String NumberFlight="00000";
  static String FlightDate='0000';
  static String Flightime="00000";
  static String taxamount;
  static String groupid;
static double inn=0.0;
  static int  resid;
  static double height=100.0;
  static bool open=false;
  static bool UpdateReservation;
static List<String>imageaboutus=[];
  static String guestdate;
  static bool ReturnLocationAirport;
  static List<String>Car_Catgory_id=[];

}